-- FIXME: will be fixed
-- local core = require("ntop.core")
--
-- describe("ntop.core spawn/kill", function()
--   it("spawns and terminates a short-lived process", function()
--     local pid = core.spawn("sleep", { "0.1" })  -- shorter sleep for CI speed
--     assert.is_number(pid)
--
--     -- Verify the task is listed
--     local tasks = core.list_tasks()
--     local found = false
--     for _, t in ipairs(tasks) do
--       if t.pid == pid then
--         found = true
--         break
--       end
--     end
--     assert.is_true(found)
--
--     -- Kill and verify
--     assert.is_true(core.kill(pid, "sigterm"))
--
--     -- Give it a moment to terminate
--     vim.wait(100, function()
--       tasks = core.list_tasks()
--       for _, t in ipairs(tasks) do
--         if t.pid == pid then return false end
--       end
--       return true
--     end)
--   end)
-- end)
